# [**Basics**](https://www.javatpoint.com/python-tutorial)

## Hello world

In [ ]:
print("Hello world.")

Hello world.

In [ ]:
x=1
if x == 1:
  print("the value is : ",x)

the value is :  1

## Variables and types

--> **isinstance(object, type)**

    The isinstance() function returns True if the specified object is of the specified type, otherwise False.

    If the type parameter is a tuple, this function will return True if the object is one of the types in the tuple

--> **type(object)**

    Return the type of object

In [ ]:
mystring = "hello"
myfloat = 10.0
myint = 20

if mystring == "hello":
    print("String: %s" % mystring)
    print("string : " , mystring)
if isinstance(myfloat, float) and myfloat == 10.0:
    print("Float: %f" % myfloat)
if isinstance(myint, int) and myint == 20:
    print("Integer: %d" % myint)

print(isinstance(myint , int))

String: hello
string :  hello
Float: 10.000000
Integer: 20
True

In [ ]:
print(type(myfloat))
print(type(int(myfloat)))

<class 'float'>
<class 'int'>

In [ ]:
one = 1
two=2
three = one+two
h = "hello" + " " + "world."
print(h , three)

hello world. 3

## List

--> Lists are very similar to arrays. They can contain any type of variable, and they can contain as many variables as you wish. Lists can also be iterated over in a very simple manner.

In [ ]:
mylist = []
mylist.append(1)
mylist.append(2)
mylist.append(3)
print(mylist[0])
print(mylist[1])
print(mylist[2]) 
# print(mylist[10]) gives an error 

for x in mylist:
    print("*"*x)

1
2
3
*
**
***

In [ ]:
numbers = [1,2,3]
strings = ["hello" , "world"]
names = ["John", "Eric", "Jessica"]

second_name = names[1]

print(numbers)
print(strings)
print("The second name on the names list is %s" % second_name)

[1, 2, 3]
['hello', 'world']
The second name on the names list is Eric

## Basic Operators

In [ ]:
# Arthematic operator

print("there two numbers 10 and 3 on which \n we perform operations \n")

print(" sum : ", 10+3) # sum
print(" substraction : ",10-3) # substraction
print(" multiply : ",10*3) # multiply
print(" division : ",10/3) # Division
print(" floor : ",10//3) # floor -->  gives you quotient
print(" mod : ",10 % 3) # mod --> gives you the reminder
print(" power : ",10 ** 3) # power

there two numbers 10 and 3 on which
 we perform operations

 sum :  13
 substraction :  7
 multiply :  30
 division :  3.3333333333333335
 floor :  3
 mod :  1
 power :  1000

In [ ]:
# Using Operators with Strings


h =  "hello" + " () " + "world"
print(h)
name = "Rahul "
names = name*5
print(names)

hello () world
Rahul Rahul Rahul Rahul Rahul

In [ ]:
# Using Operators with Lists

even_numbers = [2,4,6,8]
odd_numbers = [1,3,5,7]
all_numbers = odd_numbers + even_numbers
print(all_numbers , type(all_numbers))
print([1,2,3] * 3)

[1, 3, 5, 7, 2, 4, 6, 8] <class 'list'>
[1, 2, 3, 1, 2, 3, 1, 2, 3]

--> **len(Object)**

    Return the lenght of that object/list

--> **object.count(element)** 
    
    Return the count of elemrnt

In [ ]:
x = object()
y = object()


x_list = [x] * 10
y_list = [y] * 10
big_list = x_list + y_list

print("x_list contains %d objects" % len(x_list))
print("y_list contains %d objects" % len(y_list))
print("big_list contains %d objects" % len(big_list))

if x_list.count(x) == 10 and y_list.count(y) == 10:
    print("Almost there...")
if big_list.count(x) == 10 and big_list.count(y) == 10:
    print("Great!")

x_list contains 10 objects
y_list contains 10 objects
big_list contains 20 objects
Almost there...
Great!

## String Formatting

Python uses C-style string formatting to create new, formatted strings. The "%" operator is used to format a set of variables enclosed in a "tuple" (a fixed size list), together with a format string, which contains normal text together with "argument specifiers", special symbols like "%s" and "%d".

    %s - String (or any object with a string representation, like numbers)

    %d - Integers

    %f - Floating point numbers

    %.<number of digits>f - Floating point numbers with a fixed amount of digits to the right of the dot.

    %x/%X - Integers in hex representation (lowercase/uppercase)

In [ ]:
name = "John"
age = 23
print("%s is %d years old." % (name, age))

mylist = [1,2,3]
print("A list: %s" % mylist)

John is 23 years old.
A list: [1, 2, 3]

In [ ]:
data = ("John", "Doe", 53.44)
format_string = "Hello %s %s. Your current balance is $%s."

print(format_string % data)

Hello John Doe. Your current balance is $53.44.

## Basic String Operations

    Strings are bits of text.

In [ ]:
astring = "hello rahul's world."
print(astring, " " , len(astring)) 
#calculate the lenght of string

print(astring.index("r")) 
# find the position of givven element

print(astring.count("z")) 
# count the element "z" present in the string
print(astring.count("l"))

print(astring[0:9:2]) 
# string slicing

print(astring.upper()) 
# convert string into uppercase

print(astring.lower()) 
# convert string into lowercase

print(astring.startswith("hello")) 
# check whether string start with given word or not (return true and false)

print(astring.endswith("asdfasdfasdf")) 
# check whether string end with given word or not (return true and false)

afewwords = astring.split(" ") 
# split the string and form a list 

print(afewwords)

hello rahul's world.   20
6
0
4
hlorh
HELLO RAHUL'S WORLD.
hello rahul's world.
True
False
['hello', "rahul's", 'world.']

In [ ]:
s = "Strings are awesome!"
# Length should be 20
print("Length of s = %d" % len(s))

# First occurrence of "a" should be at index 8
print("The first occurrence of the letter a = %d" % s.index("a"))

# Number of a's should be 2
print("a occurs %d times" % s.count("a"))

# Slicing the string into bits
print("The first five characters are '%s'" % s[:5]) # Start to 5
print("The next five characters are '%s'" % s[5:10]) # 5 to 10
print("The thirteenth character is '%s'" % s[12]) # Just number 12
print("The characters with odd index are '%s'" %s[1::2]) #(0-based indexing)
print("The last five characters are '%s'" % s[-5:]) # 5th-from-last to end

# Convert everything to uppercase
print("String in uppercase: %s" % s.upper())

# Convert everything to lowercase
print("String in lowercase: %s" % s.lower())

# Check how a string starts
if s.startswith("Str"):
    print("String starts with 'Str'. Good!")

# Check how a string ends
if s.endswith("ome!"):
    print("String ends with 'ome!'. Good!")

# Split the string into three separate strings,
# each containing only a word
print("Split the words of the string: %s" % s.split(" "))

Length of s = 20
The first occurrence of the letter a = 8
a occurs 2 times
The first five characters are 'Strin'
The next five characters are 'gs ar'
The thirteenth character is 'a'
The characters with odd index are 'tig r wsm!'
The last five characters are 'some!'
String in uppercase: STRINGS ARE AWESOME!
String in lowercase: strings are awesome!
String starts with 'Str'. Good!
String ends with 'ome!'. Good!
Split the words of the string: ['Strings', 'are', 'awesome!']

## Conditions

In [ ]:
x= 2
if(x==2):
  print("yes")
elif(x==1):
  print("pretty close")
else:
  print("god saves you")

yes

In [ ]:
# Boolean operators


name = "John"
age = 23
if name == "John" and age == 23:
    print("Your name is John, and you are also 23 years old.")

if name == "John" or name == "Rick":
    print("Your name is either John or Rick.")

Your name is John, and you are also 23 years old.
Your name is either John or Rick.

In [ ]:
# The "in" operator


name = "John"
if name in ["John", "Rick"]:
    print("Your name is either John or Rick.")

Your name is either John or Rick.

  the ‘is’ operator is the  identity operator that checks whether both the operands refer to the same object or not (present in the same memory location).

In [ ]:
# The 'is' operator
"""
Unlike the double equals operator "==", the "is" operator does not 
match the values of the variables, but the instances themselves
"""
x = [1,2,3]
y = [1,2,3]
z=x
print(x == y) # Prints out True
print(x is y) # Prints out False
print(z is x)

True
False
True

In [ ]:
# The "not" operator


print(not False) # Prints out True
print((not False) == (False)) # Prints out False

True
False

In [ ]:
number = 16
second_number = 0
first_array = [1,2,3]
second_array = [1,2]

if number > 15:
    print("1")

if first_array:
    print("2")

if len(second_array) == 2:
    print("3")

if len(first_array) + len(second_array) == 5:
    print("4")

if first_array and first_array[0] == 1:
    print("5")

1
2
3
4
5

## Loops

In [ ]:
# For loop


primes = [2, 3, 5, 7]
for prime in primes:
    print(prime)

2
3
5
7

In [ ]:
# Prints out the numbers 0,1,2,3,4
for x in range(5):
    print(x)

print("*"*10)
# Prints out 3,4,5
for x in range(3, 6):
    print(x)

print("*"*10)
# Prints out 3,5,7
for x in range(3, 8, 2):
    print(x)

0
1
2
3
4
**********
3
4
5
**********
3
5
7

In [ ]:
# While loop


# Prints out 0,1,2,3,4

count = 0
while count < 5:
    print(count)
    count += 1  # This is the same as count = count + 1

0
1
2
3
4

In [ ]:
#  "break" and "continue" statements


# Prints out 0,1,2,3,4

count = 0
while True:
    print(count)
    count += 1
    if count >= 5:
        break
print("*"*10)
# Prints out only odd numbers - 1,3,5,7,9
for x in range(10):
    # Check if x is even
    if x % 2 == 0:
        continue
    print(x)

0
1
2
3
4
**********
1
3
5
7
9

In [ ]:
# Prints out 0,1,2,3,4 and then it prints "count value reached 5"

count=0
while(count<5):
    print(count)
    count +=1
else:
    print("count value reached %d" %(count))

# Prints out 1,2,3,4
for i in range(1, 10):
    if(i%5==0):
        break
    print(i)
else:
    print("this is not printed because for loop is terminated because of break but not due to fail in condition")

0
1
2
3
4
count value reached 5
1
2
3
4

In [ ]:
numbers = [
    951, 402, 984, 651, 360, 69, 408, 319, 601, 485, 980, 507, 725, 547, 544,
    615, 83, 165, 141, 501, 263, 617, 865, 575, 219, 390, 984, 592, 236, 105, 942, 941,
    386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345,
    399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217,
    815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717,
    958, 609, 842, 451, 688, 753, 854, 685, 93, 857, 440, 380, 126, 721, 328, 753, 470,
    743, 527
]

# your code goes here
for number in numbers:
    if number == 237:
        break

    if number % 2 == 1:
        continue

    print(number)

402
984
360
408
980
544
390
984
592
236
942
386
462
418
344
236
566
978
328
162
758
918

## Functions

--> Functions are a convenient way to divide your code into useful blocks, allowing us to order our code, make it more readable, reuse it and save some time. Also functions are a key way to define interfaces so programmers can share their code.

In [ ]:
def sum_two_numbers(a, b ,name):
    return name +" the ans is : " +  str(a + b)

print(sum_two_numbers(5 , 10 , "rahul"))

rahul the ans is : 15

In [ ]:
# Define our 3 functions
def my_function():
    print("Hello From My Function!")

def my_function_with_args(username, greeting):
    print("Hello, %s, From My Function!, I wish you %s"%(username, greeting))

def sum_two_numbers(a, b):
    return a + b

# print(a simple greeting)
my_function()

#prints - "Hello, John Doe, From My Function!, I wish you a great year!"
my_function_with_args("John Doe", "a great year!")

# after this line x will hold the value 3!
x = sum_two_numbers(1,2)
print(x)

Hello From My Function!
Hello, John Doe, From My Function!, I wish you a great year!
3

In [ ]:

def list_benefits():
    return "More organized code", "More readable code", "Easier code reuse", 
    "Allowing programmers to share and connect code together"


def build_sentence(benefit):
    return "%s is a benefit of functions!" % benefit


def name_the_benefits_of_functions():
    list_of_benefits = list_benefits()
    for benefit in list_of_benefits:
        print(build_sentence(benefit))

name_the_benefits_of_functions()
# print(type(list_benefits()))

More organized code is a benefit of functions!
More readable code is a benefit of functions!
Easier code reuse is a benefit of functions!

## Dictionary

Python Dictionary is used to store the data in a key-value pair format. The dictionary is the data type in Python, which can simulate the real-life data arrangement where some specific value exists for some particular key. It is the mutable data-structure. The dictionary is defined into element Keys and values.

- Keys must be a single element
- Value can be any type such as list, tuple, integer, etc.

In [ ]:
mydic = {"name" : "rahul" , "age" : 23 , "salary" : "very little" ,
         "interest" : "data science", "cgpa" : 7.51}

print(type(mydic))
print(mydic.values())
print(mydic.keys())

print(mydic)
print(mydic["name"])
del mydic["name"]          # to delete the name key , we use "del"
mydic.pop("age")  # we can also use pop method to remove a element , pop method returns a value whereas del doesn't return any value
print(mydic)
mydic["hello"] = "world" , 1 , 2

print(mydic)

<class 'dict'>
dict_values(['rahul', 23, 'very little', 'data science', 7.51])
dict_keys(['name', 'age', 'salary', 'interest', 'cgpa'])
{'name': 'rahul', 'age': 23, 'salary': 'very little', 'interest': 'data science', 'cgpa': 7.51}
rahul
{'salary': 'very little', 'interest': 'data science', 'cgpa': 7.51}
{'salary': 'very little', 'interest': 'data science', 'cgpa': 7.51, 'hello': ('world', 1, 2)}

In [ ]:
for x in mydic:
  print(x) # prints keys
  print(mydic[x]) #prints values

salary
very little
interest
data science
cgpa
7.51
hello
('world', 1, 2)

In [ ]:
for x , y in mydic.items():
  print(x , " = ", y)

salary  =  very little
interest  =  data science
cgpa  =  7.51
hello  =  ('world', 1, 2)

- cmp(dict1, dict2) = for comparison
- str(dict) = to convert dictionary into string

In [ ]:
print(str(mydic) , type(str(mydic)))

{'salary': 'very little', 'interest': 'data science', 'cgpa': 7.51, 'hello': ('world', 1, 2)} <class 'str'>

In [ ]:
print(mydic.items())
print(mydic.get("hello"))
mydic.setdefault("name")
print(mydic)

dict_items([('salary', 'very little'), ('interest', 'data science'), ('cgpa', 7.51), ('hello', ('world', 1, 2))])
('world', 1, 2)
{'salary': 'very little', 'interest': 'data science', 'cgpa': 7.51, 'hello': ('world', 1, 2), 'name': None}

## [Built-in Function](https://www.javatpoint.com/python-built-in-functions)

 **abs() function is used to return the absolute value of a number.**

In [ ]:
integera = -65
print(integera)
print(abs(integera))

-65
65

**all() function accepts an iterable object (such as list, dictionary, etc.)**

In [ ]:

list1 = [1,2,3,4,5,6,7,8,9]
print(all(list1))
# print(all(integera))  "this line throws error because int is not iterable"

True

**bool() converts a value to boolean(True or False) using the standard truth testing procedure**

In [ ]:
print(bool(0))
print(bool(1))
print(bool(10))
print(bool())

False
True
True
False

**compile() function takes source code as input and returns a code object which can later be executed by exec() function.**

In [ ]:
code_str = 'x=5 \ny=10 \nprint("sum =",x+y)'  
code = compile(code_str, 'sum.py', 'exec')  
print(type(code))  
exec(code)

<class 'code'>
sum = 15

**sum() function is used to get the sum of numbers of an iterable, i.e., list.**

In [ ]:
sum(list1)

45

**iter() function is used to return an iterator object. It creates an object which can be iterated one element at a time.**

In [ ]:
listIter = iter(list1)

print(list1)
print(next(listIter))
print(next(listIter))
print(next(listIter))
print(next(listIter))
print(next(listIter))
print(next(listIter))
print(next(listIter))
print(next(listIter))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
1
2
3
4
5
6
7
8

**The python list() creates a list in python.**

In [ ]:
string = "hello world"

print(list(string))

['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']

**map() function is used to return a list of results after applying a given function to each item of an iterable(list, tuple etc.)**

- map(function, iterables)  ==> syntax

In [ ]:
def square(n):
  return n*n

results  = sorted(set(map(square ,  list1)))
print(list1)
print(results)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 4, 9, 16, 25, 36, 49, 64, 81]

**object() returns an empty object. It is a base for all the classes and holds the built in properties and methods which are default for all the classes.**

In [ ]:
python = object()  
  
print(type(python))  
print(dir(python))

<class 'object'>
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']

**open() function opens the file and returns a corresponding file object.**

In [ ]:
# f = open("python.txt")  works in jupyter notebook

**pow() function is used to compute the powers of a number. It returns x to the power of y modulus z if a third argument(z) is present, i.e. (x, y) % z.**
- pow(x, y, z)

In [ ]:
print(pow(5,3))
print(pow(5,3,10))
print(pow(5,3,3))

125
5
2

**reversed() function returns the reversed iterator of the given sequence.**

In [ ]:
print(list(reversed(list1)))
print(list(reversed("hello world")))

[9, 8, 7, 6, 5, 4, 3, 2, 1]
['d', 'l', 'r', 'o', 'w', ' ', 'o', 'l', 'l', 'e', 'h']

**range() function returns an immutable sequence of numbers starting from 0, increments by 1 and ends at a specified number.**

- range(start , end , jump)

In [ ]:
print(list(range(5 , 13)))
print(list(range(5 , 13 , 3)))
print(list(range(-13, 0 )))

[5, 6, 7, 8, 9, 10, 11, 12]
[5, 8, 11]
[-13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1]

**round() function rounds off the digits of a number and returns the floating-point number**

- round(number,digits)

In [ ]:
print(round(2.675, 2))  
print(round(10.7))

2.67
11

**zip() function returns a zip object, which maps a similar index of multiple containers. It takes iterables (can be zero or more), makes it an iterator that aggregates the elements based on iterables passed, and returns an iterator of tuples.**

In [ ]:
rs1 = list(zip(list1 , results))
print(rs1)

[(1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81)]

**divmod() function is used to get quotient and  remainder of two numbers**
- divmod(num1 , num2)

In [ ]:
print(divmod(10,2))

x,y = divmod(8 , 5)
print(x,y)

(5, 0)
1 3

**filter() function** is used to get filtered elements. This function takes two arguments, first is a function and the second is iterable. The filter function returns a sequence from those elements of iterable for which function returns True.

The first argument can be None if the function is not available and returns only elements that are True. 

- filter (function, iterable)

In [ ]:
def mulof3(val):  
    if val%3==0:  
        return val   
result = filter(mulof3,(1,3,5,6,8,9,12,14))   
result = list(result)  
print(result) # multiples of 3

[3, 6, 9, 12]

**help() function is used to get help related to the object passed during the call.**

In [ ]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.

    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.

**slice() function is used to get a slice of elements from the collection of elements. Python provides two overloaded slice functions.**

- slice (stop)  
- slice (start, stop, step)

In [ ]:
word = "hello world this is rahul"
print(word[slice(9)])
print(word[slice(3 , 19 ,2)])
print(word[slice(-1, 1, -1)])

hello wor
l ol hsi
luhar si siht dlrow oll

**Python sorted() function is used to sort elements. By default, it sorts elements in ascending order but can be sorted descending also**

- sorted (iterable, cmp , key, reverse)

In [ ]:
li = [(2,15),(3,5),(65,5),(8,5)]  

lisorted  = sorted(li, key=lambda x: sum(x))
print(lisorted)

[(3, 5), (8, 5), (2, 15), (65, 5)]

**input ==> to take input from users**

In [ ]:
inp = input("enter your name : ")
print("hello "+ inp)

enter your name : rahul
hello rahul

## [Lambda Function](https://www.javatpoint.com/python-lambda-functions)

Lambda Functions in Python are anonymous functions, implying they don't have a name. The def keyword is needed to create a typical function in Python, as we already know. We can also use the lambda keyword in Python to define an unnamed function

In [ ]:
lb1 =  lambda x: sum(x)
print(lb1(list1))

lb2 = lambda x: x*x
print(lb2(9))

45
81

**lambda with filter**

In [ ]:
lb3 = list(filter(lambda x : (x%2 == 0) , range(1 , 16)))
print(lb3)

[2, 4, 6, 8, 10, 12, 14]

**lambda with map**

In [ ]:
lb4 =  list(map(lambda x : x*10 , list1))
print(lb4)

[10, 20, 30, 40, 50, 60, 70, 80, 90]

**lambda with zip function**

In [ ]:
lb5 = list(zip(map(lambda x: x*x , list1) , list1))
print(lb5)

[(1, 1), (4, 2), (9, 3), (16, 4), (25, 5), (36, 6), (49, 7), (64, 8), (81, 9)]

**Lambda Function with List Comprehension**

In [ ]:
squares = [lambda num = num: num ** 2 for num in range(0, 11)]  
   
for square in squares:  
    print( square(), end = " ")

0 1 4 9 16 25 36 49 64 81 100

**Lambda Function with if-else**

In [ ]:
Minimum = lambda x, y : x if (x < y) else y  
   
print(Minimum( 35, 74 ))

35

## Exceptions

**Try and Except Statement**

In [ ]:
exlist = "hello this is rahul"
exlist = exlist.split(" ")
print(exlist)
print(type(exlist))
print(exlist[0])
try:
  for i in range(5):
    print(i , " : " , exlist[i])
except:
  print("index out of range")

['hello', 'this', 'is', 'rahul']
<class 'list'>
hello
0  :  hello
1  :  this
2  :  is
3  :  rahul
index out of range

**Raise an Exception**

In [ ]:
  if len(list1) >10:
    raise Exception(f"the lenght is greater than 5 , the lenght of your list is {len(list1)}")

## Date and Time

The datetime classes are classified in the six main classes.

    date - It is a naive ideal date. It consists of the year, month, and day as attributes.
-----------------------------------------------------------
    time - It is a perfect time, assuming every day has precisely 24*60*60 seconds. It has hour, minute, 
    second, microsecond, and tzinfo as attributes.
-----------------------------------------------------------
    datetime - It is a grouping of date and time, along with the attributes year, month, day, hour, minute, second, microsecond, and tzinfo.
-----------------------------------------------------------
    timedelta - It represents the difference between two dates, time or datetime instances to microsecond resolution.
-----------------------------------------------------------
    tzinfo - It provides time zone information objects.
-----------------------------------------------------------
    timezone - It is included in the new version of Python. It is the class that implements the tzinfo abstract base class.

In [ ]:
import time

print(time.localtime(time.time()))

time.struct_time(tm_year=2022, tm_mon=8, tm_mday=22, tm_hour=9, tm_min=27, tm_sec=52, tm_wday=0, tm_yday=234, tm_isdst=0)

In [ ]:
print(time.asctime(time.localtime(time.time())))

Mon Aug 22 09:30:03 2022

In [ ]:
for i in range(5):
  print(i)
  time.sleep(1)

0
1
2
3
4
5
6
7
8
9

In [ ]:
import datetime

print(datetime.datetime.now())

2022-08-22 09:33:41.259952

In [ ]:
import calendar

cal =  calendar.month(2022 , 8)
print(cal)
print(type(cal))
print(list(cal))

    August 2022
Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30 31

<class 'str'>
[' ', ' ', ' ', ' ', 'A', 'u', 'g', 'u', 's', 't', ' ', '2', '0', '2', '2', '\n', 'M', 'o', ' ', 'T', 'u', ' ', 'W', 'e', ' ', 'T', 'h', ' ', 'F', 'r', ' ', 'S', 'a', ' ', 'S', 'u', '\n', ' ', '1', ' ', ' ', '2', ' ', ' ', '3', ' ', ' ', '4', ' ', ' ', '5', ' ', ' ', '6', ' ', ' ', '7', '\n', ' ', '8', ' ', ' ', '9', ' ', '1', '0', ' ', '1', '1', ' ', '1', '2', ' ', '1', '3', ' ', '1', '4', '\n', '1', '5', ' ', '1', '6', ' ', '1', '7', ' ', '1', '8', ' ', '1', '9', ' ', '2', '0', ' ', '2', '1', '\n', '2', '2', ' ', '2', '3', ' ', '2', '4', ' ', '2', '5', ' ', '2', '6', ' ', '2', '7', ' ', '2', '8', '\n', '2', '9', ' ', '3', '0', ' ', '3', '1', '\n']

In [ ]:
s = calendar.prcal(2022)

                                  2022

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2          1  2  3  4  5  6          1  2  3  4  5  6
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       7  8  9 10 11 12 13
10 11 12 13 14 15 16      14 15 16 17 18 19 20      14 15 16 17 18 19 20
17 18 19 20 21 22 23      21 22 23 24 25 26 27      21 22 23 24 25 26 27
24 25 26 27 28 29 30      28                        28 29 30 31
31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3                         1             1  2  3  4  5
 4  5  6  7  8  9 10       2  3  4  5  6  7  8       6  7  8  9 10 11 12
11 12 13 14 15 16 17       9 10 11 12 13 14 15      13 14 15 16 17 18 19
18 19 20 21 22 23 24      16 17 18 19 20 21 22      20 21 22 23 24 25 26
25 26 27 28 29 30         23 24 25 26 27 28 29      27 28 29 30
                          30 31

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3       1  2  3  4  5  6  7                1  2  3  4
 4  5  6  7  8  9 10       8  9 10 11 12 13 14       5  6  7  8  9 10 11
11 12 13 14 15 16 17      15 16 17 18 19 20 21      12 13 14 15 16 17 18
18 19 20 21 22 23 24      22 23 24 25 26 27 28      19 20 21 22 23 24 25
25 26 27 28 29 30 31      29 30 31                  26 27 28 29 30

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2          1  2  3  4  5  6                1  2  3  4
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       5  6  7  8  9 10 11
10 11 12 13 14 15 16      14 15 16 17 18 19 20      12 13 14 15 16 17 18
17 18 19 20 21 22 23      21 22 23 24 25 26 27      19 20 21 22 23 24 25
24 25 26 27 28 29 30      28 29 30                  26 27 28 29 30 31
31

## [Regex](https://www.geeksforgeeks.org/python-regex/?ref=gcse)

**MetaCharacters**

    \	 ==>   Used to drop the special meaning of character following it
    []	==> 	Represent a character class
    ^	==> 	Matches the beginning
    $	==> 	Matches the end
    .	==> 	Matches any character except newline
    |	==> 	Means OR (Matches with any of the characters separated by it.
    ?	==> 	Matches zero or one occurrence
    *	==> 	Any number of occurrences (including 0 occurrences)
    +	==> 	One or more occurrences
    {}	==> 	Indicate the number of occurrences of a preceding RegEx to match.
    ()	==> 	Enclose a group of RegEx

# List Comprehension